INVESTMENT_RULES = {
    "benjamin_graham": {
        "formulas": {
            "intrinsic_value": "EPS * (8.5 + 2 * g)",
            "net_current_asset_value": "Current_Assets - Total_Liabilities",
            "margin_of_safety": "(Intrinsic_Value - Current_Price) / Current_Price",
            "price_to_ncav": "Current_Price / (Current_Assets - Total_Liabilities)",
            "graham_number": "(22.5 * EPS * Book_Value_Per_Share) ** 0.5",
        },
        "checklist": [
            "PE ratio should be less than the average of the last 3 years",
            "Debt-to-equity ratio should be less than 1.0",
            "Current ratio should be greater than 1.5",
            "Earnings stability: positive earnings every year for the past 10 years",
            "Dividend record: uninterrupted dividend payments for at least 20 years",
            "Earnings growth: minimum 30% increase in per-share earnings over the past 10 years",
            "Price should not exceed 1.5 times net asset value (or PE * Price/Book < 22.5)",
            "Price should be less than 2/3 of net current asset value (NCAV)",
            "Stock should be purchased at a price below its intrinsic value (margin of safety)",
            "Avoid growth stocks with P/E ratios above 15-20",
            "Prefer large, established, and consistently profitable companies",
            "Look for companies with strong financial position and minimal debt",
        ],
        "screening_criteria": {
            "max_pe_ratio": 15,
            "max_debt_to_equity": 1.0,
            "min_current_ratio": 1.5,
            "min_years_positive_earnings": 10,
            "min_years_dividend_payments": 20,
            "min_10yr_earnings_growth_pct": 30,
            "max_price_to_book": 1.5,
            "max_pe_to_price_to_book_product": 22.5,
        },
        "strategy": "Defensive value investing. Buy stocks trading at a significant discount to their intrinsic value with a margin of safety. Focus on large, established companies with strong fundamentals, stable earnings, and consistent dividends. Avoid speculative growth stocks.",
    },
    "peter_lynch": {
        "formulas": {
            "peg_ratio": "PE_Ratio / Earnings_Growth_Rate",
            "payout_ratio": "Dividends_Per_Share / EPS",
            "debt_to_equity": "Total_Liabilities / Shareholders_Equity",
            "inventory_to_sales_ratio": "Inventory / Sales",
            "free_cash_flow_yield": "Free_Cash_Flow / Market_Cap",
            "adjusted_peg": "PE_Ratio / (Dividend_Yield + Earnings_Growth_Rate)",
        },
        "checklist": [
            "PEG ratio should be less than 1.0 (stock is undervalued relative to growth)",
            "Inventory growth should not exceed sales growth",
            "Debt-to-equity ratio should be less than 0.8 for most companies",
            "P/E ratio should be less than the earnings growth rate",
            "Prefer companies with strong free cash flow",
            "Check the company category: Fast Grower (20-25%+ growth), Stalwart (10-19% growth), Slow Grower (2-5% growth)",
            "Fast Growers: small, aggressive companies with growth 20-25% - buy before they become too popular",
            "Stalwarts: large, established companies with 10-19% growth - buy on dips",
            "Slow Growers: mature companies with 2-5% growth - check for dividend yield and payout ratio",
            "Cyclicals: companies whose sales and profits rise and fall regularly - time your entry at the bottom of the cycle",
            "Turnarounds: companies that have been beaten down but are recovering - check if they have cash to survive",
            "Asset Plays: companies with hidden assets not reflected in the stock price",
            "Cash and cash equivalents should exceed debt per share for asset plays",
            "Dividend yield should be sustainable (payout ratio < 50% for slow growers)",
            "A company should be able to do something dull (chips, bottles) or something exciting (tech) - but investors should understand the business",
            "Avoid the hottest stock in the hottest industry (often overvalued)",
            "Look for companies that are increasing their market share",
            "Avoid companies with 0% institutional ownership (may indicate problems)",
        ],
        "screening_criteria": {
            "max_peg_ratio": 1.0,
            "max_debt_to_equity": 0.8,
            "max_inventory_growth_vs_sales_growth": 0.0,
            "growth_rates": {
                "fast_grower_min": 20,
                "fast_grower_max": 25,
                "stalwart_min": 10,
                "stalwart_max": 19,
                "slow_grower_min": 2,
                "slow_grower_max": 5,
            },
            "max_payout_ratio_for_dividend_stocks": 50,
        },
        "strategy": "Growth at a reasonable price (GARP). Categorize every stock into one of six categories (Fast Grower, Stalwart, Slow Grower, Cyclical, Turnaround, Asset Play) and apply the appropriate strategy. A stock must pass the 'buy what you know' test - understand the business before investing. The PEG ratio is the primary valuation tool: PEG < 1 means undervalued.",
    },
    "warren_buffett": {
        "formulas": {
            "owner_earnings": "Net_Income + Depreciation_Amortization - Maintenance_Capex",
            "return_on_equity": "Net_Income / Shareholders_Equity",
            "debt_to_equity": "Total_Liabilities / Shareholders_Equity",
            "operating_margin": "Operating_Income / Revenue",
            "earnings_per_share_growth": "((EPS_Current / EPS_Past) ** (1 / Years) - 1) * 100",
            "intrinsic_value_dcf": "Sum of discounted future owner earnings over 10 years + terminal value",
            "book_value_growth_rate": "((BVPS_Current / BVPS_Past) ** (1 / Years) - 1) * 100",
        },
        "checklist": [
            "Return on Equity (ROE) should be consistently above 15% for at least 5-10 years",
            "Debt-to-equity ratio should be low (preferably less than 0.5)",
            "Strong and consistent operating margins (above 15%)",
            "Earnings should be consistently growing over the past 10 years",
            "Company should have a durable competitive advantage (economic moat)",
            "Brand strength: strong customer loyalty and pricing power",
            "Management should be honest, competent, and shareholder-oriented",
            "Company should have predictable and understandable business model (circle of competence)",
            "Look for companies with low capital expenditure requirements relative to earnings",
            "Owner earnings should be strong and growing (true earnings power)",
            "Book value per share should grow consistently over time",
            "Company should have pricing power (can raise prices without losing customers)",
            "Avoid businesses that require constant capital spending to stay competitive",
            "Avoid companies with excessive executive compensation or poor capital allocation",
            "Buy wonderful businesses at a fair price, not fair businesses at a wonderful price",
            "Margin of safety: intrinsic value should be significantly above current price",
            "Look for companies with net share repurchases (management confidence)",
            "Prefer companies with consistent dividend history (not necessarily high yield)",
        ],
        "screening_criteria": {
            "min_roe": 15.0,
            "max_debt_to_equity": 0.5,
            "min_operating_margin": 15.0,
            "min_years_consistent_earnings": 10,
            "min_earnings_growth_rate": 5.0,
            "min_owner_earnings_growth": 5.0,
        },
        "strategy": "Buy wonderful businesses at a fair price. Focus on companies with durable competitive advantages (moats), strong management, predictable earnings, and high returns on capital. The key is to estimate intrinsic value using owner earnings and discounted cash flow analysis, then purchase when the market price offers a sufficient margin of safety. Hold for the long term - 'our favorite holding period is forever.'",
    },
}
